# Generated by Django 6.0.2 on 2026-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('printer_queue', models.CharField(default='fiery', help_text='LPD queue name or IPP URI', max_length=200)),
                ('media_type', models.CharField(blank=True, help_text="e.g. 'Coated', 'Uncoated'", max_length=100)),
                ('media_size', models.CharField(blank=True, help_text="e.g. '12.5x19'", max_length=50)),
                ('duplex', models.CharField(choices=[('simplex', 'Simplex (1-sided)'), ('duplex_long', 'Duplex Long-Edge'), ('duplex_short', 'Duplex Short-Edge')], default='simplex', max_length=20)),
                ('color_mode', models.CharField(choices=[('color', 'Color'), ('grayscale', 'Grayscale')], default='color', max_length=20)),
                ('tray', models.CharField(blank=True, max_length=50)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('extra_lpr_options', models.TextField(blank=True, help_text='Additional -o key=value options, one per line')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Routing Preset',
                'verbose_name_plural': 'Routing Presets',
                'ordering': ['name'],
            },
        ),
    ]
