# Generated by Django 6.0.2 on 2026-03-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_routingpreset_fiery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingpreset',
            name='extra_lpr_options',
            field=models.TextField(blank=True, help_text='Additional raw -o key=value options, one per line'),
        ),
        migrations.AlterField(
            model_name='routingpreset',
            name='fiery_options',
            field=models.JSONField(blank=True, default=dict, help_text="Fiery PPD options sent as -o key=value pairs (e.g. {'EFMediaType': 'Plain'})"),
        ),
    ]
