# Generated by Django 6.0.2 on 2026-04-14 14:04

import apps.brand_assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending).')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Primary Blue'", max_length=100)),
                ('hex_value', models.CharField(help_text='Hex color code including #, e.g. #1A2B3C', max_length=7)),
                ('cmyk_label', models.CharField(blank=True, help_text="Optional CMYK values, e.g. 'C:100 M:80 Y:0 K:20'", max_length=40)),
                ('pantone_label', models.CharField(blank=True, help_text="Optional Pantone swatch name, e.g. 'PMS 286 C'", max_length=40)),
                ('rgb_label', models.CharField(blank=True, help_text="Optional RGB values, e.g. 'R:26 G:43 B:60'", max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending).')),
            ],
            options={
                'verbose_name': 'Brand Color',
                'verbose_name_plural': 'Brand Colors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('svg_file', models.FileField(help_text='Upload the asset as an SVG file.', upload_to=apps.brand_assets.models._svg_upload_path)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='brand_assets.brandassetcategory')),
            ],
            options={
                'verbose_name': 'Brand Asset',
                'verbose_name_plural': 'Brand Assets',
                'ordering': ['order', 'name'],
            },
        ),
    ]
