# Generated by Django 6.0.2 on 2026-03-07 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutter', '0001_initial'),
        ('impose', '0001_initial'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='jobs/originals/')),
                ('imposed_file', models.FileField(blank=True, null=True, upload_to='jobs/imposed/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('imposed', 'Imposed'), ('routing', 'Routing'), ('sent', 'Sent'), ('error', 'Error')], default='pending', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('page_width', models.DecimalField(blank=True, decimal_places=3, help_text='Points', max_digits=8, null=True)),
                ('page_height', models.DecimalField(blank=True, decimal_places=3, help_text='Points', max_digits=8, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutter_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='cutter.cutterprogram')),
                ('imposition_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='impose.impositiontemplate')),
                ('routing_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='routing.routingpreset')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
