# Generated by Django 6.0.2 on 2026-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='is_double_sided',
            field=models.BooleanField(default=False, help_text='Print on both sides of the sheet (duplex)'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='pages_are_unique',
            field=models.BooleanField(default=True, help_text='Each page has unique content; uncheck for step-and-repeat / stack-cut (Duplo)'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='product_type',
            field=models.CharField(blank=True, choices=[('business_card', 'Business Card'), ('postcard', 'Postcard'), ('rack_card', 'Rack Card'), ('flyer', 'Flyer'), ('brochure', 'Brochure / Booklet'), ('envelope', 'Envelope'), ('sticker', 'Sticker / Label'), ('other', 'Other')], max_length=100),
        ),
    ]
