# Generated by Django 6.0.2 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_printjob_is_double_sided_printjob_pages_are_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='is_saved',
            field=models.BooleanField(default=False, help_text='Mark this job to keep it beyond the 30-day auto-cleanup window.'),
        ),
    ]
