# Generated by Django 6.0.2 on 2026-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='preflight_acknowledged',
            field=models.BooleanField(default=False, help_text='Operator has reviewed and dismissed the preflight modal.'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='preflight_messages',
            field=models.JSONField(blank=True, default=list, help_text='User-facing Ember messages for each triggered rule.'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='preflight_notes',
            field=models.JSONField(blank=True, default=list, help_text='Internal/operator-facing notes from preflight.'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='preflight_rules_triggered',
            field=models.JSONField(blank=True, default=list, help_text="List of rule IDs that fired (e.g. ['R3', 'R8'])."),
        ),
        migrations.AddField(
            model_name='printjob',
            name='preflight_status',
            field=models.CharField(blank=True, help_text='ok / warn / error, or empty if not yet run.', max_length=10),
        ),
    ]
