# Generated by GitHub Copilot (manual) on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_preflight_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='preflight_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image filenames associated with each preflight message.'),
        ),
    ]
