# Generated by Django 6.0.2 on 2026-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_printjob_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='fit_mode',
            field=models.CharField(choices=[('cover', 'Stretch to cover bleed'), ('center', 'Center within cut size')], default='cover', help_text="How artwork fills the selected canvas: 'cover' stretches it to fill trim + bleed; 'center' fits it inside the cut size, centred.", max_length=10),
        ),
    ]
