# Generated by Django 6.0.2 on 2026-03-13 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMergeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('artwork_file', models.FileField(help_text='Postcard artwork PDF (one page = one card design).', upload_to='mailmerge/artwork/')),
                ('csv_file', models.FileField(help_text='USPS Intelligent Mail CSV with address and IMb data.', upload_to='mailmerge/csv/')),
                ('output_file', models.FileField(blank=True, help_text='Generated mail-merged PDF (one page per recipient).', null=True, upload_to='mailmerge/output/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('record_count', models.PositiveIntegerField(blank=True, help_text='Number of address records in the CSV.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Merge Job',
                'verbose_name_plural': 'Mail Merge Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
