# Generated by Django 6.0.2 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmergejob',
            name='addr_x_in',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Address block left edge, in inches from the left of the card. Defaults to card_width - 4.5 in when blank.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='addr_y_in',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Address block bottom edge, in inches from the bottom of the card. Defaults to 2.5 in when blank.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='artwork_page_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of pages detected in the uploaded artwork PDF.', null=True),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='card_height',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Finished card height in PDF points.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='card_width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Finished card width in PDF points (derived from artwork page).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='merge_page',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-based index of the artwork page that receives the address block.'),
        ),
        migrations.AlterField(
            model_name='mailmergejob',
            name='artwork_file',
            field=models.FileField(help_text='Postcard artwork PDF (1 or 2 pages — front and/or address side).', upload_to='mailmerge/artwork/'),
        ),
    ]
