# Generated by Django 6.0.2 on 2026-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0002_add_card_size_and_address_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmergejob',
            name='address_pdf_file',
            field=models.FileField(blank=True, help_text='Address step-and-repeat PDF (one sheet per N records).', null=True, upload_to='mailmerge/output/'),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='gangup_cols',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of columns in the artwork gang-up grid.', null=True),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='gangup_file',
            field=models.FileField(blank=True, help_text='Artwork gang-up PDF (N-up press sheet, for use as Fiery master).', null=True, upload_to='mailmerge/output/'),
        ),
        migrations.AddField(
            model_name='mailmergejob',
            name='gangup_rows',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of rows in the artwork gang-up grid.', null=True),
        ),
    ]
