# Generated by Django 6.0.2 on 2026-03-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0003_add_gangup_and_address_pdf_fields'),
        ('mailmerge', '0003_add_owner'),
    ]

    operations = [
    ]
