# Generated by Django 6.0.2 on 2026-03-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0004_merge_20260313_2144'),
        ('mailmerge', '0005_add_impose_template'),
    ]

    operations = [
    ]
