# Generated by Django 6.0.2 on 2026-03-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0006_merge_20260313_2231'),
        ('mailmerge', '0006_merge_20260313_2249'),
    ]

    operations = [
    ]
