# Generated by Django 6.0.2 on 2026-03-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0007_merge_20260313_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBlockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_card_width_in', models.DecimalField(decimal_places=4, default=6.0, help_text='Card width used in the preview on the defaults page (inches).', max_digits=7)),
                ('preview_card_height_in', models.DecimalField(decimal_places=4, default=9.0, help_text='Card height used in the preview on the defaults page (inches).', max_digits=7)),
                ('addr_x_in', models.DecimalField(blank=True, decimal_places=4, help_text='Default left edge of address block in inches from card left. Leave blank to use card_width − 4.5".', max_digits=7, null=True)),
                ('addr_y_in', models.DecimalField(blank=True, decimal_places=4, help_text='Default bottom edge of address block in inches from card bottom. Leave blank to use 2.5".', max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Address Block Config',
                'verbose_name_plural': 'Address Block Config',
            },
        ),
    ]
