# Generated by Django 6.0.2 on 2026-03-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0008_add_address_block_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressblockconfig',
            name='addr_block_width_in',
            field=models.DecimalField(decimal_places=4, default=4.25, help_text='Width of the address block in inches (for preview only).', max_digits=7),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='csv_fields',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of CSV column keys to include in the address block (bottom-to-top). Leave empty to use all default USPS fields.'),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='font_name',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Helvetica-Oblique', 'Helvetica Italic'), ('Helvetica-BoldOblique', 'Helvetica Bold Italic'), ('Times-Roman', 'Times Roman'), ('Times-Bold', 'Times Bold'), ('Courier', 'Courier'), ('Courier-Bold', 'Courier Bold')], default='Helvetica', help_text='PDF Type1 built-in font for address text.', max_length=60),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='font_size',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Address text font size in points.', max_digits=5),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='line_height',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Vertical spacing between address lines in points.', max_digits=5),
        ),
    ]
