# Generated by Django 6.0.2 on 2026-03-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0009_add_font_and_box_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressblockconfig',
            name='barcode_font_size',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Point size for the USPS IMb barcode line (encodedimbno field). 14pt renders the barcode at USPS-spec dimensions.', max_digits=5),
        ),
    ]
