# Generated by Django 6.0.2 on 2026-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0010_add_barcode_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressblockconfig',
            name='barcode_x_in',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Left edge of the IMb barcode from card left (inches). Leave blank to use the main address block X position.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='barcode_y_in',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Bottom baseline of the IMb barcode from card bottom (inches). Leave blank to use the main address block Y position.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='tray_font_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Font size for the tray ID text (points). Leave blank to use the main address font size.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='tray_x_in',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Left edge of the presort tray ID from card left (inches). Leave blank to include tray ID in the normal address block flow.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='addressblockconfig',
            name='tray_y_in',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Bottom baseline of the presort tray ID from card bottom (inches). Leave blank to include tray ID in the normal address block flow.', max_digits=7, null=True),
        ),
    ]
