# Generated by Django 6.0.2 on 2026-03-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmerge', '0011_separate_barcode_tray_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressblockconfig',
            name='address_template',
            field=models.TextField(blank=True, default='', help_text="Multiline address block template. Each line is printed top-to-bottom. Use {field_name} for CSV fields; plain text for static lines like 'Address Service Requested'. Leave blank to use csv_fields ordering."),
        ),
    ]
