# Generated by Django 6.0.2 on 2026-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('layout_type', models.CharField(choices=[('2up', '2-Up'), ('4up', '4-Up'), ('8up', '8-Up'), ('cut_stack', 'Cut & Stack'), ('step_repeat', 'Step & Repeat'), ('business_card', 'Business Card (21-up)'), ('postcard', 'Postcard'), ('rack_card', 'Rack Card'), ('custom', 'Custom')], max_length=20)),
                ('sheet_width', models.DecimalField(decimal_places=3, help_text='Points (1 pt = 1/72 in)', max_digits=8)),
                ('sheet_height', models.DecimalField(decimal_places=3, help_text='Points', max_digits=8)),
                ('bleed', models.DecimalField(decimal_places=3, default=0, help_text='Points', max_digits=6)),
                ('margin_top', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('margin_right', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('margin_bottom', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('margin_left', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('barcode_x', models.DecimalField(blank=True, decimal_places=3, help_text='Barcode X position in points', max_digits=8, null=True)),
                ('barcode_y', models.DecimalField(blank=True, decimal_places=3, help_text='Barcode Y position in points', max_digits=8, null=True)),
                ('columns', models.PositiveSmallIntegerField(default=1)),
                ('rows', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imposition Template',
                'verbose_name_plural': 'Imposition Templates',
                'ordering': ['name'],
            },
        ),
    ]
