# Generated by Django 6.0.2 on 2026-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impositiontemplate',
            name='cut_height',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Finished cut height in points', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='impositiontemplate',
            name='cut_width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Finished cut width in points (1 pt = 1/72 in)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='impositiontemplate',
            name='bleed',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Bleed in points (uniform, all sides)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='impositiontemplate',
            name='layout_type',
            field=models.CharField(blank=True, choices=[('2up', '2-Up'), ('4up', '4-Up'), ('8up', '8-Up'), ('cut_stack', 'Cut & Stack'), ('step_repeat', 'Step & Repeat'), ('business_card', 'Business Card (21-up)'), ('postcard', 'Postcard'), ('rack_card', 'Rack Card'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
