# Generated by Django 6.0.2 on 2026-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0002_impositiontemplate_cut_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impositiontemplate',
            name='barcode_height',
            field=models.DecimalField(decimal_places=3, default=25.2, help_text='Code 39 barcode block height in points (DC-646 default: 25.2 pt = 0.35")', max_digits=8),
        ),
        migrations.AddField(
            model_name='impositiontemplate',
            name='barcode_width',
            field=models.DecimalField(decimal_places=3, default=90.0, help_text='Code 39 barcode block width in points (DC-646 default: 90 pt = 1.25")', max_digits=8),
        ),
        migrations.AlterField(
            model_name='impositiontemplate',
            name='barcode_x',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Barcode X position in points (left edge of barcode block, from left of sheet)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='impositiontemplate',
            name='barcode_y',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Barcode Y position in points (bottom edge of barcode block, from bottom of sheet)', max_digits=8, null=True),
        ),
    ]
