# Generated by Django 6.0.2 on 2026-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0003_add_barcode_width_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='impositiontemplate',
            name='category',
            field=models.CharField(blank=True, help_text="Optional category for grouping templates (e.g. 'Business Cards', 'Postcards')", max_length=100),
        ),
        migrations.AddField(
            model_name='impositiontemplate',
            name='print_barcode',
            field=models.BooleanField(default=True, help_text='Print the barcode overlay on this layout. Uncheck if the barcode position overlaps artwork (the barcode number will still appear in the filename sent to the Fiery).'),
        ),
    ]
