# Generated by Django 6.0.2 on 2026-03-08 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0002_cutterprogram_barcode_fields'),
        ('impose', '0004_add_category_and_print_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='impositiontemplate',
            name='cutter_program',
            field=models.ForeignKey(blank=True, help_text='Barcode program to stamp on each sheet when imposing this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposition_templates', to='cutter.cutterprogram'),
        ),
    ]
