# Generated by Django 6.0.2 on 2026-03-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0005_add_cutter_program_to_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('width', models.DecimalField(decimal_places=3, help_text='Width in points (1 pt = 1/72 in)', max_digits=8)),
                ('height', models.DecimalField(decimal_places=3, help_text='Height in points', max_digits=8)),
                ('size_type', models.CharField(choices=[('cut', 'Cut Size (Finished Product)'), ('sheet', 'Sheet Size (Press Sheet)'), ('both', 'Cut & Sheet')], default='both', help_text='Whether this size is used for cut sizes, sheet sizes, or both', max_length=10)),
            ],
            options={
                'verbose_name': 'Print Size',
                'verbose_name_plural': 'Print Sizes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='impositiontemplate',
            name='cut_size',
            field=models.ForeignKey(blank=True, help_text='Named cut size (finished product dimensions) from the lookup table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_cut', to='impose.printsize'),
        ),
        migrations.AddField(
            model_name='impositiontemplate',
            name='sheet_size',
            field=models.ForeignKey(blank=True, help_text='Named sheet size (press sheet dimensions) from the lookup table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_sheet', to='impose.printsize'),
        ),
        migrations.AddField(
            model_name='impositiontemplate',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Product category from the lookup table (e.g. Bookmarks, Postcards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposition_templates', to='impose.productcategory'),
        ),
    ]
