# Generated by Django 6.0.2 on 2026-03-12 20:36

from django.db import migrations, models


def normalise_layout_types(apps, schema_editor):
    """Set any legacy layout_type value that is not 'step_repeat' to 'custom'."""
    ImpositionTemplate = apps.get_model("impose", "ImpositionTemplate")
    ImpositionTemplate.objects.exclude(layout_type="step_repeat").update(
        layout_type="custom"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0008_add_routing_preset_to_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impositiontemplate',
            name='category',
        ),
        migrations.RunPython(normalise_layout_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='impositiontemplate',
            name='layout_type',
            field=models.CharField(blank=True, choices=[('step_repeat', 'Step & Repeat'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
