# Generated by Django 6.0.2 on 2026-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0012_drop_orphaned_rules_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsize',
            name='canva_template_url',
            field=models.URLField(blank=True, help_text='Canva template URL for this print size', max_length=500),
        ),
        migrations.AddField(
            model_name='printsize',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional preview image for this size (shown in upload UI)', null=True, upload_to='print_sizes/thumbnails/'),
        ),
    ]
