# Generated by Django 6.0.2 on 2026-04-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0013_add_thumbnail_canva_to_print_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsize',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group this size under a product category (e.g. Postcards, Business Cards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_sizes', to='impose.productcategory'),
        ),
    ]
