# Generated by Django 6.0.2 on 2026-04-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0014_add_category_to_print_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='impositiontemplate',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Published templates are visible on the public Templates page.'),
        ),
        migrations.AddField(
            model_name='printsize',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Published sizes appear on the public Templates page.'),
        ),
    ]
