import requests
import os
import sys
import csv
import argparse
from dotenv import load_dotenv

# Allow `from apps.mailmerge._csv_headers import ...` when run as a standalone
# script from the project root (e.g. `python apps/mailmerge/pco-pull.py <id>`).
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from apps.mailmerge._csv_headers import CSV_HEADERS  # noqa: E402

# Load environment variables
load_dotenv()

CLIENT_ID = os.environ.get('PLANNING_CENTER_CLIENT_ID')
SECRET = os.environ.get('PLANNING_CENTER_SECRET')
BASE_URL = 'https://api.planningcenteronline.com/people/v2'


def get_list_people(list_id):
    """
    Fetches all people in a specific PCO list, including their addresses.
    """
    if not CLIENT_ID or not SECRET:
        print("Error: Missing PLANNING_CENTER_CLIENT_ID or PLANNING_CENTER_SECRET in .env")
        sys.exit(1)

    # ?include=addresses bundles the address data in the same API call
    url = f"{BASE_URL}/lists/{list_id}/people?include=addresses"
    people_data = []
    
    print(f"Fetching people for List ID {list_id}...")
    
    while url:
        response = requests.get(url, auth=(CLIENT_ID, SECRET))
        
        if response.status_code != 200:
            print(f"Error: API returned status code {response.status_code}")
            print(response.text)
            sys.exit(1)
            
        data = response.json()
        
        # Build a dictionary of addresses from the 'included' array
        # Key: Address ID, Value: Address Attributes
        addresses = {}
        for included_item in data.get('included', []):
            if included_item.get('type') == 'Address':
                addresses[included_item['id']] = included_item['attributes']
                
        # Process each person
        for person in data.get('data', []):
            person_id = person['id']
            name = person['attributes']['name']
            
            # Find the person's primary address
            primary_address = None
            address_relationships = person.get('relationships', {}).get('addresses', {}).get('data', [])
            
            for addr_ref in address_relationships:
                addr_data = addresses.get(addr_ref['id'])
                if addr_data and addr_data.get('primary'):
                    primary_address = addr_data
                    break # Found the primary, stop looking
            
            people_data.append({
                'id': person_id,
                'name': name,
                'address': primary_address
            })
            
        url = data.get('links', {}).get('next')
        
    return people_data

def generate_mailing_csv(list_id, people):
    """
    Formats the PCO data into the specific CSV structure requested.
    """
    filename = f"mailing_list_{list_id}.csv"
    
    with open(filename, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.DictWriter(file, fieldnames=CSV_HEADERS)
        writer.writeheader()
        
        for index, person in enumerate(people, start=1):
            row = {header: '' for header in CSV_HEADERS} # Initialize all columns as blank
            
            # Basic Info
            row['no'] = index
            row['name'] = person['name']
            row['contactid'] = person['id']
            
            # Address Info
            addr = person['address']
            if addr:
                row['primary street'] = (addr.get('street_line_1') or '').strip()
                row['sec-primary street'] = (addr.get('street_line_2') or '').strip()

                city = addr.get('city') or ''
                state = addr.get('state') or ''
                zip_code = addr.get('zip') or ''
                
                row['primary city'] = city
                row['primary state'] = state
                row['primary zip'] = zip_code
                
                # Create the combined city-state-zip string
                if city or state or zip_code:
                    row['city-state-zip'] = f"{city} {state} {zip_code}".strip()

            # Note: Fields like 'imbno', 'presorttrayid', 'company', etc. remain blank 
            # as they are generated by USPS CASS/Presort software, not PCO.
            
            writer.writerow(row)
            
    print(f"Successfully exported {len(people)} records to {filename}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export a PCO List to a Mailing CSV")
    parser.add_argument("list_id", help="The ID of the Planning Center List")
    args = parser.parse_args()
    
    people = get_list_people(args.list_id)
    generate_mailing_csv(args.list_id, people)
