# Generated by Django 6.0.2 on 2026-04-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Default', max_length=100)),
                ('color_per_page', models.DecimalField(decimal_places=4, default='0.0500', help_text='Cost per color page (one side)', max_digits=8)),
                ('bw_per_page', models.DecimalField(decimal_places=4, default='0.0100', help_text='Cost per black & white page (one side)', max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost Rate',
                'verbose_name_plural': 'Cost Rates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiery_job_id', models.CharField(blank=True, db_index=True, help_text='Job ID as reported by the Fiery', max_length=100)),
                ('username', models.CharField(db_index=True, help_text='Username as reported in the Fiery log (any user, not just Ember users)', max_length=255)),
                ('job_name', models.CharField(blank=True, max_length=500)),
                ('printed_at', models.DateTimeField(db_index=True, help_text='When the job completed on the Fiery')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('color_pages', models.PositiveIntegerField(default=0)),
                ('bw_pages', models.PositiveIntegerField(default=0)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('color_mode', models.CharField(choices=[('color', 'Color'), ('bw', 'Black & White'), ('mixed', 'Mixed')], default='color', max_length=10)),
                ('media_size', models.CharField(blank=True, max_length=100)),
                ('media_type', models.CharField(blank=True, max_length=100)),
                ('duplex', models.BooleanField(default=False)),
                ('calculated_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Total cost of this job at the time of calculation', max_digits=10, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw log entry from Fiery for reference')),
                ('cost_rate', models.ForeignKey(blank=True, help_text='Rate snapshot used when cost was calculated', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.costrate')),
            ],
            options={
                'verbose_name': 'Print Log Entry',
                'verbose_name_plural': 'Print Log',
                'ordering': ['-printed_at'],
                'indexes': [models.Index(fields=['username', 'printed_at'], name='tracking_pr_usernam_a0c844_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fiery_job_id__gt', '')), fields=('fiery_job_id',), name='unique_fiery_job_id_nonempty')],
            },
        ),
    ]
