# Generated by Django 6.0.2 on 2026-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower number = higher priority')),
                ('condition_type', models.CharField(choices=[('page_size', 'Page Size (WxH pts)'), ('page_count', 'Page Count'), ('filename', 'Filename Pattern'), ('product_type', 'Product Type')], max_length=30)),
                ('condition_value', models.CharField(help_text='Value to match (exact or pattern)', max_length=255)),
                ('action_type', models.CharField(choices=[('apply_template', 'Apply Imposition Template'), ('assign_cutter', 'Assign Cutter Program'), ('route_to_printer', 'Route to Printer Preset')], max_length=30)),
                ('action_value', models.CharField(help_text='ID or name of the target object', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
