# Generated by Django 6.0.2 on 2026-03-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0001_initial'),
        ('impose', '0001_initial'),
        ('routing', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Ruleset', 'verbose_name_plural': 'Rulesets'},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='action_value',
        ),
        migrations.AddField(
            model_name='rule',
            name='cutter_program',
            field=models.ForeignKey(blank=True, help_text='Cutter / barcode program to assign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='cutter.cutterprogram'),
        ),
        migrations.AddField(
            model_name='rule',
            name='imposition_template',
            field=models.ForeignKey(blank=True, help_text='Gangup / imposition template to apply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='impose.impositiontemplate'),
        ),
        migrations.AddField(
            model_name='rule',
            name='routing_preset',
            field=models.ForeignKey(blank=True, help_text='Printer preset to route to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='routing.routingpreset'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='condition_type',
            field=models.CharField(choices=[('page_size', 'Page Size (W×H in)'), ('page_count', 'Page Count'), ('filename', 'Filename Pattern'), ('product_type', 'Product Type')], max_length=30),
        ),
    ]
