# Generated by Django 6.0.2 on 2026-03-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0006_add_print_size_product_category'),
        ('rules', '0002_alter_rule_options_remove_rule_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='cut_size',
            field=models.ForeignKey(blank=True, help_text='Filter templates by this cut size', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_cut', to='impose.printsize'),
        ),
        migrations.AddField(
            model_name='rule',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Filter templates by this product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='impose.productcategory'),
        ),
        migrations.AddField(
            model_name='rule',
            name='sheet_size',
            field=models.ForeignKey(blank=True, help_text='Filter templates by this sheet size', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_sheet', to='impose.printsize'),
        ),
    ]
