# Generated by Django 6.0.2 on 2026-03-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impose', '0006_add_print_size_product_category'),
        ('rules', '0003_add_size_category_filters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name'], 'verbose_name': 'Ruleset', 'verbose_name_plural': 'Rulesets'},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='condition_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='condition_value',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='priority',
        ),
        migrations.AlterField(
            model_name='rule',
            name='cut_size',
            field=models.ForeignKey(blank=True, help_text='Cut size (finished product dimensions) for this ruleset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_cut', to='impose.printsize'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Product category for this ruleset (e.g. Bookmarks, Postcards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='impose.productcategory'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sheet_size',
            field=models.ForeignKey(blank=True, help_text='Sheet size (press sheet dimensions) for this ruleset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_sheet', to='impose.printsize'),
        ),
    ]
